version: "3.3"
services:
  cups:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cups
    ports:
      - "631:631"
    volumes:
      - .:/workspaces/cups
      - ./container-config:/etc/cups
      - ./container-config/logs:/var/log/cups
